services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: application

  application:
    image: user_management:latest
    depends_on:
      - mysql
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./env.example:/var/www/.env